import * as _array from './array'
import * as _base from './base'
import * as _equal from './equal'
import * as _guards from './guards'
import * as _is from './is'
import * as _math from './math'
import * as _string from './string'
import * as _time from './time'
import * as _types from './types'
import * as _function from './function'
import * as _object from './object'
import * as _promise from './promise'
import * as _vendor from './vendor'
import * as _p from './p'

export const utils = { array: _array, base: _base, equal: _equal, guards: _guards, is: _is, math: _math, string: _string, time: _time, types: _types, function: _function, object: _object, promise: _promise, vendor: _vendor, p: _p }
// export default utils

export * from './array'
export * from './base'
export * from './equal'
export * from './guards'
export * from './is'
export * from './math'
export * from './string'
export * from './time'
export * from './types'
export * from './function'
export * from './object'
export * from './promise'
export * from './vendor'
export * from './p'
